version: "3.3"
services:
  database:
    image: mariadb:latest
    container_name: mariadb_dbmovie
    volumes:
      - mariadb_dbmovie_volume:/var/lib/mariadb
      - ./db_scripts:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dbmovie
      MYSQL_USER: movie
      MYSQL_PASSWORD: password
  java:
    container_name: java_movie
    build: .
    ports:
      - "8081:8080"
volumes:
  mariadb_dbmovie_volume: {}
